# -*- coding: utf-8 -*-
"""activitat_25_juny.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVEyTeJXcal8Kz3d_J1nvi-2QdpnGrnr
"""

'''
1-Invertir el valor d'una cadena:
a)Assignar a una variable una cadena de text qualsevol, després crear una altra variable de text
buida on haurem de fer el procés per passar els valors de e l'anterior cadena però invertida.
b) Mostrar els caràcters d'una cadena en ordre invers
'''

# método 1
cadena = "mi casa es de color azul"
cadena2 = ''

for palabra in cadena:
  #for car in palabra:
    cadena2 = palabra + cadena2
print(cadena2)

# método 2
cadena = "mi casa es de color azul"
cadena2 = ''
for posicio in range(len(cadena)):
  #for letra in cadena[posicio]:
    cadena2 = cadena[posicio] + cadena2
print(cadena2)

# método 3
cadena = "mi casa es de color azul"
cadena2 = ''

for fila in range(len(cadena)):
  #for columna in range(len(cadena[fila])):
    cadena2 =  cadena[fila] + cadena2
print(cadena2)

'''
2-Comptar lletres:
Comptar el número de vegades que surt la lletra 'a' dins d'una cadena de text.
'''

# método 1

cadena = "amo de tu casa y amo de mi casa"
contador = 0
for letra in range(len(cadena)):
  if cadena[letra] in 'a':
#if cadena[letra] == 'a':
    contador += 1
print(contador)

#método 2

cadena = "amo de tu casa y amo de mi casa"
contador = 0
for letra in cadena:
  if letra in 'a':
 # if letra == 'a':
    contador +=1
print(contador)

#método 3
cadena = "amo de tu casa y amo de mi casa"
contador = 0
for fila in range(len(cadena)):
  if cadena[fila] == 'a':
    contador += 1
print(contador)

'''
6-Dissenya un programa que demani una paraula i l'escrigui per pantalla tantes vegades com la seva
 longitud:
exemple:
Exemple:

'''
#método 1
cadena = input("Entra una paraula: ")
for posicio in range(len(cadena)):
  print(cadena)

#método 2

cadena = input("Entra una paraula: ")

for letra in cadena:
  print(cadena)

#método 3
cadena = input("Entra una paraula: ")

for fila in range(len(cadena)):
  print(cadena)

'''
12.  Escriu un programa que rebi 2 cadenes i ens digui si la primera cadena està dins de l'altra.
user-bash$ python 11trobarcadena.py 'el' 'la casa no estaba'    --> Treu per pantalla: La
cadena 'el' NO està dins de 'la casa no estaba'
user-bash$ python 11trobarcadena.py 'el' 'l
'''

#método 1

cadena1 = input("escriu 1ª cadena : ")
cadena2 = input("Escriu 2ª cadena: ")

if cadena2 in cadena1:
  print("la cadena2 está en la cadena1")
else:
  print('no está en la cadena 1')

#método 2


cadena1 = input("escriu 1ª cadena : ")
cadena2 = input("Escriu 2ª cadena: ")

if cadena2 in cadena1:
  print("la cadena2 está en la cadena1")
else:
  print('no está en la cadena 1')

# método 3

cadena1 = input("escriu 1ª cadena : ")
cadena2 = input("Escriu 2ª cadena: ")

#for fila in range(len(cadena1)):
if cadena2 in cadena1:
  print("la cadena2 está en la cadena1")
else:
  print('no está en la cadena 1')

'''
Subcadena 1- Dissenya un programa que tregui tots els prefixes d'una cadena que rebem per paràmetre.
Per exemple la cadena "Fedora" treu per pantalla:
F
Fe
Fed
Fedo
Fedor
Fedora

'''
cadena = input("entra una palabra: ")
cadena2 = ''
for letra in cadena:
  cadena2 =  cadena2 + letra
  print(cadena2)

